//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Draeger.Dynamics365.Testautomation.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Draeger.Dynamics365.Testautomation.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die var IsElementHasScrollbar = function(element) {
        ///
        ///    if (element.tagName === document.scrollingElement.tagName &amp;&amp; typeof window.innerWidth === &quot;number&quot;) {
        ///        var scrollHeight = Math.max(
        ///            document.body.scrollHeight, document.documentElement.scrollHeight,
        ///            document.body.offsetHeight, document.documentElement.offsetHeight,
        ///            document.body.clientHeight, document.documentElement.clientHeight
        ///        );
        ///
        ///        return scrollHeight &gt; document.documentElement.clientHe [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string GetAllElementsWithScrollBars {
            get {
                return ResourceManager.GetString("GetAllElementsWithScrollBars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die function absoluteXPath(element) {
        ///    var comp;
        ///    var comps = [];
        ///    var xpath = &quot;&quot;;
        ///    var getPos = function(element) {
        ///        var position = 1, curNode;
        ///        if (element.nodeType == Node.ATTRIBUTE_NODE) {
        ///            return null;
        ///        }
        ///        for (curNode = element.previousSibling; curNode; curNode = curNode.previousSibling) {
        ///
        ///            if (curNode.nodeName == element.nodeName) {
        ///                ++position;
        ///            }
        ///        }
        ///        return position;
        ///    };
        ///
        ///    if ( [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string GetElementAbsolutXPath {
            get {
                return ResourceManager.GetString("GetElementAbsolutXPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die var GetElementWithActiveScrollBar = function(elements) {
        ///    var jQueryElements = $(elements);
        ///    if (jQueryElements.length === 0) return null;
        ///    if (jQueryElements.first().get(0) === document.scrollingElement) return jQueryElements.get(0);
        ///    if (jQueryElements.length === 1) return jQueryElements.get(0);
        ///    var scrollBarsHeight = jQueryElements.map(function() {
        ///        return $(this)[0].scrollHeight;
        ///    });
        ///    var scrollBarWithMaxHeight = Math.max.apply(null, scrollBarsHeight.toArray());
        ///   [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string GetElementWithActiveScrollbar {
            get {
                return ResourceManager.GetString("GetElementWithActiveScrollbar", resourceCulture);
            }
        }
    }
}
